### ISSUE TITLE
Make no_std

### ISSUE THREAD

**Issue by garro95** [garro95/priority-queue#15]

**Comment by Ben-PH** [comment]
is this issue still active? I'm interested in making head-way - have a specific use in mind.

**Comment by garro95** [comment]
This was waiting for IndexMap to be no_std

**Comment by garro95** [comment]
The no_std branch contains an implementation of no_std. I am still not satisfied with it because the usage of some methods (from and from_iter) became less straight-forward. I am trying to understand how to make them easy again like they do in `indexmap`
