### ISSUE TITLE
Float as Priority 

### ISSUE THREAD

**Issue by TianyiShi2001** [garro95/priority-queue#27]
I'm writing [the Dijkstra's Shortest Path Algorithm](https://www.youtube.com/watch?v=pSqmAO-m7Lk&list=PLDV1Zeh2NRsDGO4--qE8yH72HFL1Km93P&index=18) which uses the priority queue. Some distances within the graph, which are represented by `f32` or `f64`, are needed to be used as the priority. However, this is not allowed because floats implement only `PartialOrd`. Is there any workarounds to this?

**Comment by garro95** [comment]
The workaround is to define a "new type" (https://doc.rust-lang.org/rust-by-example/generics/new_types.html) like this:
```rust
#[derive(PartialOrd, PartialEq)]
struct MyF64(f64)

impl Eq for MyF64 {}

impl Ord for MyF64 {
    fn cmp(&self, other: &Self) -> Ordering {
	if let Some(ordering) = self.partial_cmp(other) {
	    ordering
	} else {
	    // Choose what to do with floats, for example:
	    Ordering::Less
	}
    }
}
```

**Comment by TianyiShi2001** [comment]
Thank you! I've just found a crate that specifically provides ordered floats: https://github.com/reem/rust-ordered-float
