### ISSUE TITLE
Function to remove item with least priority

### ISSUE THREAD

**Issue by zyansheep** [garro95/priority-queue#30]
Something like `PriorityQueue::pop()` but it removes the item with the least priority instead of the most priority. I was looking at the code and thought this could be accomplished by using VecDeque instead of Vec (since VecDeque allows for popping from both sides), but I don't know enough to know where to even start implementing it.
Perhaps creating a new type called `PriorityDeque` would be a good idea.
For the time being, I will just set my priorities to `usize::MAX - priority` to take advantage of the `.pop()` function and then do it back so I can use my initial priority values.

**Comment by garro95** [comment]
If you need reverse order (i.e. a Priority queue where the item with the minimum priority is the first to be extracted), use [`Reverse<T>`](https://doc.rust-lang.org/std/cmp/struct.Reverse.html)

**Comment by garro95** [comment]
@zyansheep Did my answer satisfy your needs?

**Comment by zyansheep** [comment]
Oh, that works. Thanks!

**Comment by zyansheep** [comment]
For anyone else looking at this issue, here is what I did:
```rust
let priority_queue = PriorityQueue<Value, Reverse<usize>> // Will reverse the ordering of the priority values
```

**Comment by garro95** [comment]
Probably I should be more explicit in the documentation. Some examples may help

**Comment by imgeorgiev** [comment]
Hey, I am having a similar issue but I would like to be able to pop the items with the highest or lowest priority from the queue. AFAIK, currently, you can create a PriorityQueue that can do only one of the two but not both at the same time. Maybe it's worth implementing a `pop_back()` as well?

**Comment by garro95** [comment]
It can be done, but it requires a different data structures.In fact, the Priority queue is never guaranteed to be fully sorted.

To be able to do that, a DoublePriorityQueue is needed, that would have two heaps of indices sharing the same items map. The two heaps need to be kept in sync with respect to insertions and removal. All of this will have a cost in terms of performance.
