### ISSUE TITLE
Add a pop_lowest_priority API

### ISSUE THREAD

**Issue by Luni-4** [garro95/priority-queue#39]
It would be helpful to add a pop API that extracts the lowest priority from the queue and not only the greatest one (as documented [here](https://docs.rs/priority-queue/latest/priority_queue/priority_queue/struct.PriorityQueue.html#method.pop))

**Comment by garro95** [comment]
If you need a `PriorityQueue` that can extract at any time the greatest or the lowest priority, you can use the [`DoublePriorityQueue`](https://docs.rs/priority-queue/latest/priority_queue/double_priority_queue/struct.DoublePriorityQueue.html) data structure.

If you always want to extract the minimum priority item, you can wrap your priorities in a standard wrapper called [`Reverse<T>`](https://doc.rust-lang.org/std/cmp/struct.Reverse.html)

**Comment by Luni-4** [comment]
Oh, thank you! Could you please provide some examples in README or inside the examples directory about these two patterns you just mentioned? That would be really helpful! Thank you!

**Comment by rikonor** [comment]
@Luni-4 I needed this too - here's an example:
```rs
let mut pq: PriorityQueue<String, Reverse<u64>> = PriorityQueue::new();

pq.push("1".into(), Reverse(10));
pq.push("2".into(), Reverse(15));
```
