### ISSUE TITLE
Bug in DoublePriorityQueue.peek_min()

### ISSUE THREAD

**Issue by testforvln** [garro95/priority-queue#42]
After thounds of loops using change_priority() functions, I met with result of peek_min() function not returning the min priority item. 

Has anyone come across this situation?

**Comment by garro95** [comment]
Are you able to reproduce the issue with a minimal example?

**Comment by garro95** [comment]
@testforvln  Can I add your code, modified, to the test suite of DoublePriorityQueue?

**Comment by garro95** [comment]
Thanks for your contribution. Version 1.3.1 has been released, that includes the fix for this bug
