### ISSUE TITLE
Add option for duplicate/unhashable Items

### ISSUE THREAD

**Issue by dhouck** [garro95/priority-queue#44]
Sometimes you want map values which are unhashable/incomparable, and sometimes you want to allow duplicates.  For a project I was working on (since refactored), I would need to change the values in a way that altered there hashes.

All of this can be made to work with a `struct` like

```rust
#[derive(Debug)]
pub struct Node<T> {
    nonce: u64,
    pub value: T,
}
```
where the implementation ensures that `nonce` is always unique (a simple counter would do along with a manual implementation of `Clone`) and only `nonce` participates in hashing and equality (which is why I donʼt `derive` `Hash`, `PartialEq`, or even `Eq` (because the derivable one requires `T: Eq` even though this isnʼt needed)); they can be implemented manually or with the [`derivative` crate](https://crates.io/crates/derivative)).

The harder part is making an ergonomic UI to handle this, and I donʼt have enough of a handle on ergonomic Rust to design one at the moment (which is why this is an issue not a PR).

**Comment by garro95** [comment]
I think you cannot have the feature that you need and at the same time an efficient function to change the priority of an item (how would you identify it in case of duplicates?).

If you don't ever need to retrieve the (item, priority) tuple by item, then you can probably use the [`BinaryHeap`](https://doc.rust-lang.org/std/collections/struct.BinaryHeap.html) instead, that is more efficient than the data structure implemented by this trait for that use case, as also shown in the benchmarks

**Comment by dhouck** [comment]
I know I considered it and rejected it for some reason, but I donʼt remember what.  But that does look like it should work for at least most use cases.
