### ISSUE TITLE
Use complex data structure as Priority

### ISSUE THREAD

**Issue by sigsegved** [garro95/priority-queue#49]
I have an use case where I want to track an estimated rate as the priority for items tracked in PriorityQueue. Lets assume this structure looks as follows. 

```rust 
pub struct Rate {
  estimated_rate: f64,
  last_update_time: f64
}

Following code snippet summarizes my problem.
// assume we have functions that update the estimated rate based on the last updated time and current time. 
```

```rust
let pq = PriorityQueue::<String, Rate>::new();

let rate = Rate::new();
let curr_time = 123.0;
rate.record(100.0, curr_time);
pq.insert("key1".to_string(), rate);

// now if i want to update the priority of this item
let entry = pq.get_mut("key1".to_string());
// now the Priority returned is a non mutable reference. 
// which means I can't call `entry.1.record(200.0, curr_time);`
```

How can i best model this with the PriorityQueue data structure?

**Comment by garro95** [comment]
As stated in the documentation (https://docs.rs/priority-queue/latest/priority_queue/priority_queue/struct.PriorityQueue.html#method.get_mut), to update the priority of an item use one of the `change_priority`, `change_priority_by` or `push`.
