### ISSUE TITLE
Consider changing license to MIT or Apache 2.0

### ISSUE THREAD

**Issue by ckaran** [garro95/priority-queue#5]
From the [rust API guidelines](https://rust-lang-nursery.github.io/api-guidelines/necessities.html#crate-and-its-dependencies-have-a-permissive-license-c-permissive):

```
The software produced by the Rust project is dual-licensed, under either the 
MIT or Apache 2.0 licenses.  Crates that simply need the maximum 
compatibility with the Rust ecosystem are recommended to do the same, in 
the manner described herein...
```

I don't know if you ever plan on submitting `priority-queue` to become part of the standard library, but the license could become a stumbling block, especially if you get other contributors (at the moment it appears that no-one else has contributed, so you own the copyright and can change the license at will).

**Comment by garro95** [comment]
I don't like that licenses, so I prefer to follow all the other guidelines but this one.

**Comment by ckaran** [comment]
@garro95 Why don't you like the license?  Full disclosure, I'm the guy that wrote the Army Research Laboratory's [Open Source policy](https://github.com/USArmyResearchLab/ARL-Open-Source-Guidance-and-Instructions), and I like to know why developers like or don't like a particular license.  We're in the process of updating our policy again as we've learned a lot about what works and what doesn't work, and I'd like to incorporate any helpful opinions I can.
