### ISSUE TITLE
ahash < 0.8.7 broken on nightly

### ISSUE THREAD

**Issue by andrewbaxter** [garro95/priority-queue#52]
Per https://github.com/tkaitchuck/aHash/issues/200

The dep chain I see is
```
ahash v0.7.7
└── hashbrown v0.12.3
    └── indexmap v1.9.3
        └── priority-queue v1.4.0
            └── ...
```
ahash through indexmap are using ^0.8 (I think) on their latest releases, but for indexmap that must be 2.x which isn't supported here yet.

For more context, I think I need nightly to do wasm builds (to change panic behavior).

**Comment by garro95** [comment]
An update to `indexmap` v2 is in progress and will likely land soon

**Comment by garro95** [comment]
priority-queue 2.0.0 has been released with updated dependency on IndexMap ^2.0.0

**Comment by garro95** [comment]
Can you please check that the version

**Comment by andrewbaxter** [comment]
Awesome, thanks! I have some other intermediate deps that need to be updated to 2.0 with this, I'll reach out to them.
