### ISSUE TITLE
Does it support multithreading? Is it lock free?

### ISSUE THREAD

**Issue by loongs-zhang** [garro95/priority-queue#57]

**Comment by garro95** [comment]
It does not.

The algorithm needs to work on the whole tree to perform an operation (insertion, removal of the top priority item), so I think that the best thing to do to support multithreading is to lock the data structure in a `Mutex`, `RwLock` or use channels or similar primitives to control the access.

If anyone is aware of alternative algorithms that can perform lock-free operations on a heap, please let me know
