### ISSUE TITLE
remove elements at arbitrary positions

### ISSUE THREAD

**Issue by Trolldemorted** [garro95/priority-queue#9]
I know that this might be out of scope for a traditional priority queue, but what do you think of supporting removing elements at arbitrary positions?

I'd like to track cached chunks in a priority queue (least priority -> first to be dropped when a different chunk is no longer needed and moved to the cache), and when a chunk is moved into the "real" data structure it needs to be removed from the cache priority queue to prevent it from being removed too early.

**Comment by garro95** [comment]
Sorry for answering so late. This can be done, but I don't know if I can do it in short times. If you want, you could implement this feature yourself and open a pull request. If you chose to do this, write some tests for the new feature too

**Comment by Ben-PH** [comment]
I have a similar desire: remove elements by some sort of ID

**Comment by garro95** [comment]
In the master branch there is a preliminary implementation of a remove function. Please check that it works as expected and tell me if it suits your needs.
